DROP SCHEMA IF EXISTS MAIN;
CREATE SCHEMA MAIN AUTHORIZATION SA;

DROP TABLE IF EXISTS MAIN.PROFILE;
CREATE TABLE MAIN.PROFILE (
  id UUID PRIMARY KEY,
  update_date TIMESTAMP,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  membership_date DATE,
  membership_statu VARCHAR(250),
  premium_membership_expiry_date DATE
);

DROP TABLE IF EXISTS MAIN.SUPPORT_REQUEST;
CREATE TABLE MAIN.SUPPORT_REQUEST (
  id UUID PRIMARY KEY,
  update_date TIMESTAMP,
  profile_id UUID,
  subject VARCHAR(250),
  message VARCHAR(500)
);

DROP TABLE IF EXISTS MAIN.DEBIT_CARD;
CREATE TABLE MAIN.DEBIT_CARD (
  id UUID PRIMARY KEY,
  update_date TIMESTAMP,
  profile_id UUID,
  name VARCHAR(20),
  no VARCHAR(30),
  expiry_date VARCHAR(5),
  cvc VARCHAR(3)
);
